on:
  pull_request:
    branches:
    - PROD

jobs:
  DEV:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nrwl/nx-set-shas@v3
      - run: npm install -g pnpm
      - name: Install packages
        run: pnpm install --frozen-lockfile
        
      - run: npx nx run hugomeet:lint:test
