on:
  pull_request:
    branches:
    - PROD
  push:
    branches:
    - DEV

env:
  NX_PROJECT_API_ENDPOINT: https://project-api.hugocabel.com
  NX_TELEMETRY_API_ENDPOINT: https://api-telemetry.hugocabel.com

jobs:
  install-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Cache node modules
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: cache-node-modules-${{ hashFiles('pnpm-lock.yaml') }}
      - name: install pnpm
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install -g pnpm
      - name: pnpm install deps
        if: steps.cache.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile

  lint:
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: cache-node-modules-${{ hashFiles('pnpm-lock.yaml') }}
      - run: npx nx affected:lint --base=${{ github.event.before }} --parallel

  build_then_test:
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: cache-node-modules-${{ hashFiles('pnpm-lock.yaml') }}
      # - run: npx nx affected:build --base=${{ github.event.before }} --parallel
      # - run: npx nx affected:test --base=${{ github.event.before }} --parallel
      - run: npx nx build frontend-portfolio
      - run: npx nx test portfolio-e2e