on:
  pull_request:
    branches:
    - PROD

jobs:
  install-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: cache-node-modules-${{ hashFiles('pnpm-lock.yml') }}
      - name: install pnpm
        run: npm install -g pnpm
      - name: pnpm install deps
        if: steps.cache.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile

  distributed-task:
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
      - uses: actions/checkout@v3
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: cache-node-modules-${{ hashFiles('pnpm-lock.yml') }}
      - run: npx nx affected --parallel --maxParallel=4 --target=lint --base=${{ github.event.pull_request.base.sha }} --head=${{ github.event.pull_request.head.sha
